# Name of this GitHub Actions workflow.
name: Publish Docker Image

# Define the trigger for workflow to run
on: [push, pull_request]

# Define jobs
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    # Specifies where to run
    runs-on: ubuntu-latest
    # Define permissions
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    # Define the steps to be executed in this job
    steps:
      # Step to send a Discord notification at the start of the job
      - name: Discord Notification - Job Start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g # Optional avatar URL
          embed-title: "Pushing Docker Image to Docker Hub Started"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "Pushing Docker image to Docker Hub for the **${{ github.ref_name }}** branch. [View Pipeline](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

      - name: Check out the repository
        uses: actions/checkout@v4
      # Login into dockerhub using credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # extracts metadata (tags and labels) for a Docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edemeruwa/itas276-assignment1
          tags: |
            latest
            ${{ github.event.release.tag_name }}
      # Builds and pushes docker image from the github repo to dockerhub
      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # Creates an attestation with information about generated image and uplads it to dockerhub
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/edemeruwa/itas276-assignment1
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      # Step to send a Discord notification when the job completes
      - name: Discord Notification - Job Completed
        uses: tsickert/discord-webhook@v5.3.0
        if: always() # Ensures this step runs even if the job fails
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g # Optional avatar URL
          embed-title: "Push Docker Image to Docker Hub Completed"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "Pushing Docker image to Docker Hub for the **${{ github.ref_name }}** branch completed with status: **${{ job.status }}**."
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}" # Sets color based on job status
