name: Publish Docker Image

on: [push, pull_request]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Notify - Workflow Start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Workflow Started: Publish Docker Image"
          embed-description: "Triggered by **${{ github.triggering_actor }}** on branch **${{ github.ref_name }}**."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-author-name: "${{ github.repository }}"

      - name: Notify - Checkout Started
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Checking out Repository"

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Notify - Docker Login Started
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "🔑 Logging in to Docker Hub"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Notify - Metadata Extraction Started
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "🧾 Extracting Docker Metadata"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edemeruwa/itas276-assignment1
          tags: |
            latest
            ${{ github.event.release.tag_name }}

      - name: Notify - Build & Push Started
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "🔧 Building and Pushing Docker Image"

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Notify - Attestation Started
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "🛡️ Generating Artifact Attestation"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/edemeruwa/itas276-assignment1
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Upload SARIF Report (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          sarif_file: results.sarif

      - name: Notify - SARIF Uploaded
        if: always()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "📦 SARIF Report Uploaded"
          embed-description: "SARIF file uploaded. [🔽 Download SARIF](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)"

      - name: Notify - Workflow Completed
        if: always()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Repo: edemeruwa/itas276-assignment1"
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "✅ Workflow Completed"
          embed-description: "Workflow for **${{ github.ref_name }}** finished with status: **${{ job.status }}**."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}"
