# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Publish Docker Image
on: [push, pull_request]
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edemeruwa/itas276-assignment1
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha
      
      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=edemeruwa/itas276-assignment1
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
      - name: Debug build digest
        run: echo "Digest: ${{ steps.build-and-push.outputs.digest }}"
        if: success() && steps.build-and-push.outputs.digest != ''
        with:
          subject-name: index.docker.io/edemeruwa/itas276-assignment1
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
          


       
