name: Publish Docker Image

# Define the trigger for workflow to run
on: [push, pull_request]

# Define jobs
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    # Define where to run
    runs-on: ubuntu-latest
    # Define permissions
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      # Login into dockerhub using credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # extracts metadata (tags and labels) for a Docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edemeruwa/itas276-assignment1
          tags: |
            latest
            ${{ github.event.release.tag_name }}
      # Builds and pushes docker image from the github repo to dockerhub
      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # Creates an attestation with information about generated image and uplads it to dockerhub to 
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/edemeruwa/itas276-assignment1
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
