# Name of this GitHub Actions workflow.
name: Static Self-hosted Security Tests

# Define when this workflow will run
on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:
    # Trigger on any activity within a pull request
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch:
    # Allows manual triggering of the workflow
  # Scan mainline branches if there are changes to .github/workflows/semgrep.yml:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/semgrep.yml' # Only trigger if this file changes

# Set permissions for the workflow
permissions:
  contents: read # Allows the workflow to checkout your code
  security-events: write # Allows the workflow to write security events (like SARIF results)

# Define the jobs that will run as part of this workflow
jobs:
  # Job to send a Discord notification when the workflow starts
  Discord-Begin:
    # Specifies the runner environment for this job
    runs-on: ubuntu-latest
    # Define the steps to be executed in this job
    steps:
      # Step to send a Discord notification
      - name: Discord Notification - Workflow Start
        # Uses the community-maintained Discord webhook action
        uses: tsickert/discord-webhook@v5.3.0
        # Configure the action with webhook details and message content
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }} # Your Discord webhook URL stored as a secret
          username: ${{ github.repository }} # Sets the username for the Discord message
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g # Optional avatar URL
          embed-title: "Security Pipeline Started" # Title of the Discord embed
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" # Link to the specific workflow run
          embed-description: "The security analysis pipeline has started for the **${{ github.ref_name }}** branch. [View details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" # Description with a link
          embed-author-name: "${{ github.triggering_actor }}" # The GitHub user who triggered the workflow

 
  Discord-End:
    # Specifies that this job will only run after the 'semgrep' and 'snyk' jobs have completed (regardless of their status)
    needs: [Discord-Begin, semgrep, snyk]
    # Specifies the runner environment for this job
    runs-on: ubuntu-latest
    # Define the steps to be executed in this job
    steps:
      # Step to send a Discord notification
      - name: Discord Notification - Workflow Completed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }} # Your Discord webhook URL
          username: ${{ github.repository }} # Sets the username for the Discord message
          embed-title: "Security Pipeline Completed" # Title of the Discord embed
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" # Link to the specific workflow run
          embed-description: "The security analysis pipeline has completed with overall status: **${{ job.status }}**. You can find the security reports in the 'Artifacts' section of this run." # Description with a link
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}" # Sets color based on workflow status
          embed-author-name: "${{ github.triggering_actor }}" # The GitHub user who triggered the workflow
