# Name of this GitHub Actions workflow.
name: security tests

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  security-events: write

jobs:

  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

  semgrep:
    name: semgrep/ci scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --sarif > semgrep_output.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload Semgrep Output
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-output
          path: semgrep_output.sarif
      - name: Discord Notification (Job Completion)
        uses: tsickert/discord-webhook@v5.3.0
        if: always()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "SAST scan using Semgrep completed"
          embed-description: "**Semgrep scan** completed with status: **${{ job.status }}** Download the [security report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) under the 'Artifacts' section."
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}"

  snyk:
    name: snyk/docker-security scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: test --sarif --file=package.json > snyk_output.sarif || true
      - name: Upload Snyk Output
        uses: actions/upload-artifact@v4
        with:
          name: snyk-output
          path: snyk_output.sarif
      - name: Discord Notification (Job Completion)
        uses: tsickert/discord-webhook@v5.3.0
        if: always()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "SCA scan using Snyk completed"
          embed-description: "**Snyk scan** completed with status: **${{ job.status }}**"
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}"
