# Name of this GitHub Actions workflow.
name: security tests

# Triggers for this workflow: on PRs, manual dispatch, or push to main/master.
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

# Permissions for uploading security scan data
permissions:
  contents: read
  security-events: write

# Each section below defines a separate job in the pipeline.
jobs:

  # Notify at the start of the pipeline.
  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification - Workflow Started
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          embed-title: "🚀 Security Pipeline Started"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Click to view full workflow run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

  # Static Application Security Testing with Semgrep.
  semgrep:
    name: semgrep/ci scan
    runs-on: ubuntu-latest

    # Use Semgrep's official Docker container
    container:
      image: semgrep/semgrep

    # Skip scans on dependabot PRs
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: semgrep ci --sarif > semgrep_output.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload Semgrep SARIF
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-output
          path: semgrep_output.sarif

      - name: Discord Notification - Semgrep Completed
        uses: tsickert/discord-webhook@v5.3.0
        if: always()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "✅ Semgrep SAST Scan Completed"
          embed-description: |
            Semgrep completed with status: **${{ job.status }}**
            [🔗 Download SARIF output](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}"

  # Software Composition Analysis using Snyk.
  snyk:
    name: snyk/docker-security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Scan and Generate SARIF
        run: snyk test --sarif --file=package.json > snyk_output.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk SARIF
        uses: actions/upload-artifact@v4
        with:
          name: snyk-output
          path: snyk_output.sarif

      - name: Discord Notification - Snyk Completed
        uses: tsickert/discord-webhook@v5.3.0
        if: always()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "🔍 Snyk SCA Scan Completed"
          embed-description: |
            Snyk scan completed with status: **${{ job.status }}**
            [🔗 View Run #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          embed-color: "${{ job.status == 'success' && '3066993' || job.status == 'failure' && '15158332' || '9807270' }}"

