name: SAST and SCA scanning using GitHub Runner

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  semgrep:
    name: semgrep/ci scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --sarif > semgrep_output.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload Semgrep Output
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-output
          path: semgrep_output.sarif

  snyk:
    name: snyk/docker-security scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --sarif-file-output=synk_output.sarif
      - name: Upload Snyk Output
        uses: actions/upload-artifact@v4
        with:
          name: synk-output.sarif
          path: synk_output
